### PR TITLE
Fix a typo

### PR DESCRIPTION
**Pull request by wbecker**

### CODE REVIEW

**Comment by wbecker** [comment]
Hey nice job! I'm just about to re-architect my front end using Redux tomorrow, so was really super helpful, especially the bit about middle ware. Hope you don't mind all these redlines. Feel a little bit like a school teacher, but hopefully it makes it a bit friendlier on the next anankastic reader!

**Comment by wbecker** [comment]
Oh, and finish it off. You have me hanging on the end of my seat for the conclusion!

**Comment by wbecker** [comment]
Please :)

**Comment by happypoulp** [comment]
I had no doubt that my english was less than perfect... but that much ??!
That hurts my feelings :D (just kidding)

Thanks a lot for all your fixes!

I'll try to finish as soon as I can, but in the meantime, if you need missing infos, Redux's docs are more and more developing and should be able to answer your needs.

**Comment by wbecker** [comment]
Thanks for your work! I'm going through the official doco now, but this is a really nice way of framing it. 

I used to fix up people's PhD theses - this is a lot easier when you are allowed to be more colloquial...

**Comment by happypoulp** [comment]
Honestly, I didn't think that would learn so much writing this tutorial, especially not in english :D. It's awesome to have people like you joining to help! Thanks!

**Pull request merged**
