### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by astrauka**
Fixed typo, my editor removes trailing whitespaces

### CODE REVIEW

**Comment by astrauka** [comment]
@happypoulp ^^

**Comment by happypoulp** [comment]
Hey @astrauka ! Nice to see to you here :D!

Are you enjoying Redux?

Thanks for your fix ;)! (there was so many typos in this tutorial...)

**Comment by astrauka** [comment]
Still grasping on it, I am coming from backend, so need to get familiar with frontend ecosystem as well :)

**Comment by happypoulp** [comment]
I agree, frontend ecosystem and tooling can be pretty frightening at first... Hope you'll find your way in them!
See you next conf ;)!

**Pull request merged**
